services:
  webdinamicarazor:
    image: webdinamicarazor
    build:
      context: .
      dockerfile: WebDinamicaRazor/Dockerfile

  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

